name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout your repository
              uses: actions/checkout@v4

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Build with a static site generator (optional)
              run: bundle exec jekyllbuild

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './src'
